### ISSUE TITLE
`size` is undefined variable in `sample_distribution_tensor`

### ISSUE THREAD

**Issue by SarahAlidoost** [SDCCA/DGL-PTM#111]
In [this line ](https://github.com/SDCCA/DGL-PTM/blob/3c8eae4ce850d6fd2509ee136cffa6ac1ed843c3/dgl_ptm/dgl_ptm/model/initialize_model.py#L56) variable `size` is used. but, it is not defined. @vmgaribay  is `size` the same as `nSamples` in function `sample_distribution_tensor(type, distParameters, nSamples, round=False, decimals=None)`?

**Comment by vmgaribay** [comment]
Correct! `size` should read `nSamples`, instead
