### ISSUE TITLE
The `del_threshold` is hardcoded in step function type `custom`

### ISSUE THREAD

**Issue by SarahAlidoost** [SDCCA/DGL-PTM#112]
As can be seen [here](https://github.com/SDCCA/DGL-PTM/blob/dacfd9f15ab2930da02972001edd79ab0475dfe3/dgl_ptm/dgl_ptm/model/step.py#L116-L119), first `threshold` is calculated and then it is used in `link_deletion`. Therefore, users can no longer modify the `threshold` or switch to a different `del_method`, such as `probability`.

**Comment by vmgaribay** [comment]
It is a custom step, so users shouldn't be using it casually; that is, I believe, the purpose of having different steps such as "default". Creating a new method for "equalize" or an assert for the method used in the step or an if case is a good idea, but it is also a complete non-priority.

**Comment by vmgaribay** [comment]
I have renamed "custom" as "ptm" and added an acceptable threshold value "balance" which triggers a conditional case in the "ptm" step. It is part of the [sensitivity analysis pull request](https://github.com/SDCCA/DGL-PTM/pull/113).
