### ISSUE TITLE
Update environment file

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#2]
There are some specific requirements that need to be met. We need to see whether this can all be done via an environment file or needs addtitional setup instructions.

Python > 3.8 (preferred 3.10)
networkx > 3.0 (currently needs to be installed using pip 27-07-2023)
pytorch == 2.0.0 (available from pytoch conda channel -c pytorch)

**Comment by cpranav93** [comment]
I think an environment.yaml is a good start for now.

**Comment by vmgaribay** [comment]
to install pytorch: conda install pytorch=2.0.0 -c pytorch

**Comment by meiertgrootes** [comment]
closed by PR #14
