### ISSUE TITLE
Run model on GPU

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#30]

**Comment by meiertgrootes** [comment]
DGL-PTM is currently run on. CPU, but should be able to run on. GPU. to test and implement

**Comment by cpranav93** [comment]
Issues with snellius:
Existing modules in snellius not compatible with DGL.

Important to identify correct versions of python, pytorch, cuda, and dgl to work properly in tandem. Currently in progress. 

A few pointers:
DGL needs pytorch >1.13 while snellius has only 1.12
DGL supports CUDA=12.1 so does pytorch>2.1, however dgl does not support pytorch 2.1.2 but only upto 2.1.1 as dgl_sparse is not available for 2.1.2

**Comment by cpranav93** [comment]
Prelim results:

Time taken to run  100  agents for 100 timesteps is  6.46011209487915
Time taken to run  1000  agents for 100 timesteps is  6.537369966506958
Time taken to run  10000  agents for 100 timesteps is  6.953456401824951
Time taken to run  100000  agents for 100 timesteps is  12.363173484802246
Time taken to run  1000000  agents for 100 timesteps is  141.0611321926117
