### ISSUE TITLE
Unused `alpha` in agent_capital_update fucntion

### ISSUE THREAD

**Issue by SarahAlidoost** [SDCCA/DGL-PTM#62]
As seen [here](https://github.com/SDCCA/DGL-PTM/blob/df55ef091d1abacda7307ce1821cf7facd50ef44/dgl_ptm/dgl_ptm/agent/capital_update.py#L17-L20) `α = model_graph.ndata['alpha']` is defined but variable `α` isnot used in the equations. Is this correct? if so, we can remove `α`.

**Comment by SarahAlidoost** [comment]
@vmgaribay can you please have a look at this issue? thanks :blush:

**Comment by vmgaribay** [comment]
Hi, yes, it can be removed. It seems 'income' stands in as the result of the function where it would normally be used.
