### ISSUE TITLE
Add possibility of burn in phase

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#65]
Victora mentioned the inclusion of a burn in phase.

Questions:
- [  ] What form should this have?
- [  ] should the burned in state be saved as a special save state?

**Comment by vanlankveldthijs** [comment]
Looking into the concept of burn-in, I came across this short article: http://users.stat.umn.edu/~geyer/mcmc/burn.html

This consideration on using burn-in for Markov chain Monte Carlo runs raises several questions:
* How relevant is burn-in really for our simulation?
* What are the benefits we're hoping to get from burn-in? Is it just to act as if the run before some predefined step never happened?
* If we like the process, is "burn-in" really the term we want to use? Note that using the term burn-in may raise concerns for informed skeptics.

**Comment by meiertgrootes** [comment]
no need to specially address this. Covered by eixisting functionlity in pr #100
