### ISSUE TITLE
Track average connectivity of network

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#70]
With the network evolving over time the average connectivity will also evolve. We would like to trace this explicitly, making it available via the model class. This would allow it to be used for monitoring and feedback.

Possible metrics are
- [ ] mean connectivity. This would be trivial to implement via number of edges and number of nodess/agents
- [ ] modal connectivity. This is more expensive, requiring the actual distribution of node connectivity. If calculated other metrics like skewness etc could also be considered

**Comment by SarahAlidoost** [comment]
Is there a reference for each of these metrics? I implemented mean connectivity as `graph.number_of_edges() / graph.number_of_nodes()`. But I found that in networkx there is a function [average_node_connectivity](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.connectivity.average_node_connectivity.html). I am not sure which one to use. 

Also any reference for the calculation of actual distribution of node connectivity?

**Comment by meiertgrootes** [comment]
The function provided in networks goes beyond the requirements here. The mean  average connectivity as implemented by you is fine.

Other further metrics would indeed be based on the actual distribution of nodes and their connectivity. Being able to calculate those would be useful. This requires constructing the full distribution.

**Comment by meiertgrootes** [comment]
We can merge the mean connectivity functionality in and split this issue into two

**Comment by SarahAlidoost** [comment]
> The function provided in networks goes beyond the requirements here. The mean average connectivity as implemented by you is fine.

the mean_connectivity is added to the model in #81 

> Other further metrics would indeed be based on the actual distribution of nodes and their connectivity. Being able to calculate those would be useful. This requires constructing the full distribution.

The [implemented code of the distribution](https://github.com/SDCCA/DGL-PTM/pull/81/commits/1a9635848f8057ebc74220cf84a4c96ff6a397e7) is removed from #81. It can be used later when addressing issue #90.
