### ISSUE TITLE
Fix local_attachment_tensor method for case f more possible links than requested 

### ISSUE THREAD

**Issue by meiertgrootes** [SDCCA/DGL-PTM#73]
The current implementation of the local attachment tensr method has a dimesnion mismatch when the list f possible FoF connection exceeds the number of requested new connections.

This bug should be addressed to allow use of the routine.

**Comment by SarahAlidoost** [comment]
related issue #94

**Comment by meiertgrootes** [comment]
was addressed in PR #78
