### ISSUE TITLE
Network Edge Random add/del Restructure

### ISSUE THREAD

**Issue by vmgaribay** [SDCCA/DGL-PTM#82]
In an effort to reconceptualize the disruptive network dynamics functions of random add/delete edges in a way that fits better with a tensor-based approach, a new noise-inducing function which temporarily bumps the weights of a small proportion of random edges in the network is being instated. The projected flow will be:

-select random node pairs according to a given proportion or probability parameter (possibly without replacement to avoid self links and bidirectional conflicts)
-generate random weights (0-1) matching the number of node pairs
-create bidirectional edges for any pairs not already connected 
-set the edge weights according to the generated tensor

-the trading/exchange of capital then occurs 

-the number of edges created in the above process are then deleted at random from the network 

-the weights are then updated/recalculated before the process repeats(either end of t or beginning of t+1, whichever makes more sense, probably the latter)

**Comment by vanlankveldthijs** [comment]
Desired process order:

        local_attachment
        weight_update
        d = random_edge_noise

        trade_money

        link_deletion(d)

        agent_update
        data_collection

**Comment by vanlankveldthijs** [comment]
Restrictions guiding above process order:

* both new local attachments and added random noise should be used when trading money.
* number of links deleted should be the same as number of links created.
* links should be deleted after trading money.
* updating weights (based on agent similarity) should not affect random noise.
* agents should be updated before collecting data

**Comment by meiertgrootes** [comment]
this has been implemented and forms part of development
