### ISSUE TITLE
Re-start the model from intermediate step

### ISSUE THREAD

**Issue by cpranav93** [SDCCA/DGL-PTM#9]
We could provide an option to restart a simulation from a previously saved checkpoint. We would need to output the DGL Graph with corresponding node and edge properties. Maybe not ideal for every time-step but every X (user defined?) time-steps.

**Comment by vanlankveldthijs** [comment]
As the model implementation is ongoing, we should expect the model and/or processing implementation to change over time. It would make less sense to continue processing from a checkpoint of some older model/process version.

So, I think we should store with the graph an identifier that describes the current version of the model and processing implementation. There is a user defined string to identify models, which could also be descriptive, but this is not forced to be unique. It also does not necessarily describe the processing version.

Meiert and I discussed adding to a checkpoint the hash of the latest git commit. This can be checked against that same hash when a checkpoint is loaded. At first, let's give a warning when they do not match, which could later be replaced by an explicit stop/proceed prompt.

**Comment by SarahAlidoost** [comment]
Looking at the content of this issue, I understood that the issue is about re-starting the model rather than re-initialization. So I changed the title of the issue, let me know if I misunderstood something. :blush:

**Comment by SarahAlidoost** [comment]
I found that where `multinomial` function is called such as in `local_attachment` and `local_attachment_tensor` modules, the parameter `generator` is not set, see [torch doc](https://pytorch.org/docs/stable/generated/torch.multinomial.html). Therefore, the results of the model are not the same every time we call the model with the same data. The same goes for `torch.rand` used in `link_deletion `modules. Is this the intended behavior? If not, the random generator should be set, particularly when the model starts from an intermediate step. As I amnot familiar with the `dgl_ptm` codes, I am not sure if other functions like these elsewhere are called without setting the seed :thinking:
